# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastoscontrolados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(verbose_name='fecha ingreso')),
                ('importe', models.IntegerField(default=0)),
                ('permanente', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defTipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='ingresos',
            name='permanente',
            field=models.IntegerField(default=0),
        ),
    ]
