# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastoscontrolados', '0002_auto_20161117_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipo',
            name='idTipo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='fecha',
            field=models.DateField(verbose_name='fecha ingreso'),
        ),
    ]
