# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastoscontrolados', '0003_auto_20161122_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo',
            old_name='defTipo',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='gastos',
            name='permanente',
            field=models.BooleanField(default=0),
        ),
        migrations.RemoveField(
            model_name='gastos',
            name='tipo',
        ),
        migrations.AddField(
            model_name='gastos',
            name='tipo',
            field=models.ManyToManyField(to='gastoscontrolados.Tipo'),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='permanente',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Nomina'), (2, 'Loterias'), (3, 'Extra')], default=1),
        ),
    ]
