# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastoscontrolados', '0004_auto_20170222_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIngresos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTipo', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Tipo',
            new_name='TipoGastos',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='tipo',
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ttipo',
            field=models.ManyToManyField(to='gastoscontrolados.TipoIngresos'),
        ),
    ]
